# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = distance

# Source files (.c or .py)
SRC = distance.c

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin)
ARCH = x64

include $(MPY_DIR)/py/dynruntime.mk
