# This is the default variant when you `make` the Unix port.

FROZEN_MANIFEST ?= $(VARIANT_DIR)/manifest.py

MICROPY_PY_BTREE = 0
#MICROPY_PY_FFI = 0
#MICROPY_PY_SOCKET = 0
#MICROPY_PY_THREAD = 0
#MICROPY_PY_TERMIOS = 0
#MICROPY_PY_SSL = 0
#MICROPY_USE_READLINE = 0

MICROPY_VFS_FAT = 0
MICROPY_VFS_LFS1 = 0
MICROPY_VFS_LFS2 = 0
